### ISSUE TITLE
Notification Daemon Sends Duplicate Messages

### ISSUE THREAD

**Issue by Neuro-CS** [fabiansinz/pipecontrol#20]
Using either crontab or a custom python notification daemon will make duplicate requests. When the daemon only checks every five minutes, duplicate notifications appear less than five minutes later. When all crontab entries are deleted in the docker container, notifications are still sent out.

**Comment by ecobost** [comment]
@Neuro-CS was this solved? if so, please close this issue

**Comment by Neuro-CS** [comment]
You need to manually remove the cron jobs in the Docker container to get the duplicate messages fixed. I still haven't figured out how to automatically fix this issue.
